---
title: "R Notebook"
output: html_notebook
---
# git commit code
```{bash}
git status
git add distribution.Rmd samplesize.Rmd algorithm.Rmd
git commit -m  "commented out and added linear regression"
git push -u origin_3 main
```
## Assessment of the normal distribution function for different values of x and y
```{r}

x_vector = c()
y_vector = c()
vector_assess = seq.int(0.001,0.99,0.001)
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- qnorm(vector_assess[i])
  # print(y_vector)
  # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector)
```

## Sigmoid distribution function
```{r}

x_vector = c()
y_vector = c()
# vector_assess = c(-Inf,-1,0, 1, Inf)
vector_assess = c(-Inf,-100,-50,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,50,100,Inf)
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- 1/(1+(1/exp(vector_assess[i])))
  # print(y_vector)
  # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector,type = "b")
```

# Binomial function 
```{r}
binomial = function(p , q, n, x){
  p = choose(n, x) * p^x * q^(n-x)
  return(p)
}
# where
# 
# p is the probability of success
# q is the probability of failure
# x is the expected event
# n is the total number of events

vector_assess = seq.int(from = 0,to = 100,by = 1)
x_vector = c()
y_vector = c()
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- binomial(p = 0.8,q = 0.2,n = 100,x = vector_assess[i])
   # print(y_vector)
   # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector,type = "b")
```

# Normal distribution
```{r}

normal_distribution = function(x,mean,sd){
  
  y = (1/sd* sqrt(2* pi))* 1/exp(0.5 * ((x-mean)/sd)^2)
}

# where 
# mean is the average of the distribution
# sd is the standard deviation of the distribution

# vector_assess = seq.int(from = -1000,to = 1000,by = 1)
vector_assess = seq.int(from = 0,to = 100,by = 1)
x_vector = c()
y_vector = c()

for (i in seq_along(vector_assess)){
  mean = mean(vector_assess,na.rm = TRUE)
  sd = sd(vector_assess,na.rm = TRUE)
  x_vector[i] = vector_assess[i]
  y_vector[i] = normal_distribution(x=vector_assess[i],mean = mean,sd = sd)
  if (i == length(vector_assess)) {
    print(mean)
    print(sd)
  }
}


plot(x_vector,y_vector,type = "b")
```

```{r}

mean = mean(vector_assess,na.rm = TRUE)
sd = sd(vector_assess,na.rm= TRUE)
par(mfrow=c(2,2))
plot(vector_assess,dnorm(vector_assess,mean = mean,sd = sd),type = "b",xlab = "input vector",ylab = "dnorm",main = "dnorm")
plot(vector_assess,pnorm(vector_assess,mean = mean,sd = sd),type = "b",xlab = "input vector",ylab = "pnorm",main = "pnorm")
# plot(vector_assess,qnorm(vector_assess,mean = mean,sd = sd),type = "b",xlab = "input vector",ylab = "qnorm",main = "qnorm")
plot(vector_assess,rnorm(vector_assess,mean = mean,sd = sd),type = "b",xlab = "input vector",ylab = "rnorm",main = "rnorm")

# qnorm(vector_assess,mean = mean,sd = sd)
```
# Poisson distribution
```{r}
poisson_distribution = function(lambda,x){
 
  y = exp(-lambda) * lambda^x/factorial(x)
  return(y)
}

# where x is the distribution 
# lambda is the mean number of occurrences in the interval

poisson_distribution(lambda = 2,x = 3)

# vector_assess = seq.int(from = -1000,to = 1000,by = 1)
vector_assess = seq.int(from = 0,to = 10,by = 0.001)
x_vector = c()
y_vector = c()

lambda_vector = c(1,2,3,4,5,6,7,8,9)

for (i in seq_along(lambda_vector)){
for (j in seq_along(vector_assess)){
  lambda = lambda_vector[i]
  x_vector[j] = vector_assess[j]
  y_vector[j] = poisson_distribution(lambda = lambda_vector[i],x = vector_assess[j])
}
  if(i == min(seq_along(lambda_vector))){
  plot(x_vector,y_vector,type = "b")  
    # print(min(seq_along(lambda_vector)))
  }
  else{
    lines(x_vector,y_vector,type = "b",col = "blue")
  }
  

}

```
```{r}
# vector_assess = seq.int(from = 0,to = 100,by = 1)
# vector_assess = 100
# x_vector = c()
# y_vector = c()
# 
# lambda_vector = c(0.03)
# 
# for (i in seq_along(lambda_vector)){
# for (j in seq_along(vector_assess)){
#   lambda = lambda_vector[i]
#   x_vector[j] = vector_assess[j]
#   y_vector[j] = poisson_distribution(lambda = lambda_vector[i],x = vector_assess[j])
# }
#   if(i == min(seq_along(lambda_vector))){
#   plot(x_vector,y_vector,type = "b")  
#     # print(min(seq_along(lambda_vector)))
#   }
#   else{
#     lines(x_vector,y_vector,type = "b",col = "blue")
#   }
#   
# 
# }
# 
# hist(y_vector)
```



