---
title: "R Notebook"
output: html_notebook
---

```{bash}
git status
git add samplesize.Rmd
git commit -m  "Commit Message"
git push -u origin_2 main
```

# Two sample size proportion estimation

```{r}

samplesize_twosampleproportion <- function(p1,p0,alpha, beta, superiority_delta){
  num = qnorm(alpha) + qnorm(beta)
  denom = p1 - p0 - superiority_delta
  
    n = ( (p1 * (1- p1)) + (p0 * (1-p0))) * ((num)/(denom))^2
  
  return(n) 
  
}

samplesize_twosampleproportion(p1 = 0.45,p0 = 0.10,alpha = 0.05,beta = 0.2,superiority_delta = 0.05)

```
## Assessment of the normal distribution function for different values of x and y
```{r}

x_vector = c()
y_vector = c()
vector_assess = seq.int(0.001,0.99,0.001)
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- qnorm(vector_assess[i])
  # print(y_vector)
  # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector)
```
## Assessment of the sigmoid distribution function for different values of x and y
```{r}

x_vector = c()
y_vector = c()
# vector_assess = c(-Inf,-1,0, 1, Inf)
vector_assess = c(-Inf,-100,-50,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,50,100,Inf)
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- 1/(1+(1/exp(vector_assess[i])))
  # print(y_vector)
  # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector,type = "b")
```

```{r}
binomial = function(p , q, n, x){
  p = choose(n, x) * p^x * q^(n-x)
  return(p)
}


vector_assess = seq.int(from = 0,to = 100,by = 1)
x_vector = c()
y_vector = c()
for (i in seq_along(vector_assess)) {
  x_vector[i] <- vector_assess[i]
  y_vector[i] <- binomial(p = 0.8,q = 0.2,n = 100,x = vector_assess[i])
   # print(y_vector)
   # print(x_vector)
  
}

# x_vector
# y_vector

plot(x_vector,y_vector,type = "b")
```

